Extra Tests
LeilaGhaffari/my-enzyme pull request #3
Opened 2022-06-09 18:29 UTC by kellen-martin

Adds more tests using enzyme

2022-06-09 19:14 UTC, LeilaGhaffari requested changes

2022-06-09 19:14 UTC, LeilaGhaffari commented on extras/newton_enz.c
> +{
Thanks, @kellen-martin , this is great. I don't really have a style convention in this repo but I would recommend sticking with one style in your commits (and also this is a good practice for reviewing PRs). Anyways, in your `for-loops` you open the curly brace right after the condition, but here, you open it on a new line. You decide which one you'd prefer.

2022-06-09 19:56 UTC, jedbrown reviewed
Looking good. Can you add a `Makefile` to this directory to automate building? There is a simple one at `libceed-enzyme/Makefile` that can be copied over.

For formatting the C code, one option to ensure consistency is to grab [Ratel's `.clang-format`](https://gitlab.com/micromorph/ratel/-/blob/main/.clang-format), in which case vscode/clangd can auto-format.

2022-06-10 18:21 UTC, kellen-martin commented
Thanks for the help @jedbrown & @LeilaGhaffari, I have added the Makefile and reformatted using .clangformat from Ratel.

2022-06-10 18:28 UTC, LeilaGhaffari commented
Thanks, @kellen-martin for adding those files. Could you move `my-enzyme/extras/.clang-format` to `my-enzyme/` so it can impact other folders as well.

2022-06-10 18:53 UTC, LeilaGhaffari commented
Oh, you can remove `my-enzyme/extras/.clang-format` now.

2022-06-10 19:08 UTC, LeilaGhaffari commented
Great, thanks! Could you rebase your branch onto main before we merge it?
You can do it with `git pull --rebase origin main`.

2022-06-13 19:25 UTC, kellen-martin commented
Ready for final review!

2022-06-13 19:27 UTC, LeilaGhaffari approved these changes
Thanks, @kellen-martin . It looks great! You can merge it now.

2022-06-13 19:31 UTC, merged